import {
  FaBalanceScale,
  FaBrain,
  FaBuilding,
  FaChair,
  FaCloud,
  FaCode,
  FaDatabase,
  FaEnvelope,
  FaGithub,
  FaGraduationCap,
  FaHandPaper,
  FaHeart,
  FaHome,
  FaJs,
  FaLinkedin,
  FaNodeJs,
  FaPlay,
  FaReact,
  FaRocket,
  FaSearch,
  FaShoppingCart,
  FaCog,
  FaServer,
  FaChartLine,
  FaBolt,
  FaCar,
  FaPuzzlePiece,
  FaUtensils,
  FaBook,
  FaLaptopCode,
} from 'react-icons/fa';

import type {
  ContactInfo,
  Project,
  SkillCategory,
  SocialLink,
  TechStack,
} from '../types';

export const NAV_ITEMS = [
  { id: 'home', label: 'Home' },
  { id: 'about', label: 'About' },
  { id: 'projects', label: 'Projects' },
  { id: 'contact', label: 'Contact' },
] as const;

export const TECH_STACK: TechStack[] = [
  { icon: FaReact, name: 'React', color: '#61DAFB' },
  { icon: FaBolt, name: 'Svelte', color: '#FF3E00' },
  { icon: FaServer, name: 'Node.js', color: '#339933' },
  { icon: FaCloud, name: 'Azure', color: '#0078D4' },
  { icon: FaCog, name: 'AI/ML', color: '#FF6B6B' },
  { icon: FaJs, name: 'JavaScript', color: '#F7DF1E' },
  { icon: FaDatabase, name: 'SQL', color: '#336791' },
  { icon: FaRocket, name: 'Heroku', color: '#430098' },
  { icon: FaCode, name: 'Angular', color: '#DD0031' },
];

export const SOCIAL_LINKS: SocialLink[] = [
  { icon: FaGithub, url: 'https://github.com/davidagustin', label: 'GitHub' },
  {
    icon: FaLinkedin,
    url: 'https://www.linkedin.com/in/davidsyagustin/',
    label: 'LinkedIn',
  },
  { icon: FaEnvelope, url: 'mailto:davidsyagustin@gmail.com', label: 'Email' },
];

export const CONTACT_INFO: ContactInfo[] = [
  {
    icon: FaEnvelope,
    label: 'Email',
    value: 'davidsyagustin@gmail.com',
    url: 'mailto:davidsyagustin@gmail.com',
    color: '#EA4335',
  },
  {
    icon: FaLinkedin,
    label: 'LinkedIn',
    value: 'davidsyagustin',
    url: 'https://www.linkedin.com/in/davidsyagustin/',
    color: '#0077B5',
  },
  {
    icon: FaGithub,
    label: 'GitHub',
    value: 'davidagustin',
    url: 'https://github.com/davidagustin',
    color: '#333',
  },
];

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    title: 'Frontend Development',
    icon: FaReact,
    skills: [
      'React.js',
      'Next.js',
      'Angular',
      'Vue.js',
      'Svelte',
      'SvelteKit',
      'TypeScript',
      'Tailwind CSS',
      'HTML5/CSS3',
      'Material Design',
      'RxJS',
    ],
    color: '#61DAFB',
  },
  {
    title: 'Backend Development',
    icon: FaNodeJs,
    skills: [
      'Node.js',
      'Express.js',
      'Python',
      'REST APIs',
      'Database Design',
      'Authentication',
      'Firebase',
      'Firestore',
    ],
    color: '#339933',
  },
  {
    title: 'AI/ML & Data',
    icon: FaBrain,
    skills: [
      'Machine Learning',
      'Data Analysis',
      'Python Libraries',
      'AI Integration',
      'Computer Vision',
      'MediaPipe',
      'Jupyter Notebooks',
    ],
    color: '#FF6B6B',
  },
  {
    title: 'DevOps & Deployment',
    icon: FaRocket,
    skills: [
      'Git/GitHub',
      'Azure',
      'Vercel',
      'Netlify',
      'Surge.sh',
      'Render',
      'Heroku',
      'Firebase Hosting',
      'CI/CD',
      'Cloud Deployment',
    ],
    color: '#667eea',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: 'StreamFlix - Netflix/Disney+ Style Streaming App',
    description:
      'A modern streaming platform built with Next.js 15 and React, featuring a Netflix/Disney+ inspired interface with movie browsing, carousels, and responsive design. Features movie carousels, hero sections, real movie posters, and robust image fallback systems.',
    technologies: ['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS', 'AWS Amplify', 'Lucide React'],
    githubUrl: 'https://github.com/davidagustin/aws-amplify-practice',
    liveUrl: 'https://main.d1bolbr8do04cv.amplifyapp.com/',
    icon: FaPlay,
    category: 'Streaming Platform',
    features: [
      'Movie Carousels & Browsing',
      'Netflix-Style UI/UX',
      'Real Movie Posters',
      'Responsive Design',
    ],
  },
  {
    id: 2,
    title: 'Premium Auto Sales - Professional Car Sales Website',
    description:
      'A modern, professional car sales website built with Hugo and designed for GitLab Pages deployment. Features comprehensive vehicle inventory with detailed listings, contact forms, multi-language support (English, French, Persian RTL), and a premium car dealership experience with professional styling and SEO optimization.',
    technologies: ['Hugo', 'GitLab Pages', 'CSS3', 'Multi-language Support', 'SEO Optimized', 'Responsive Design'],
    githubUrl: 'https://gitlab.com/davidagustin1-group/gitlab-hugo-practice-app',
    liveUrl: 'https://gitlab-hugo-practice-app-e1b201.gitlab.io/',
    icon: FaCar,
    category: 'E-commerce/Automotive',
    features: [
      'Vehicle Inventory Management',
      'Multi-language Support',
      'Professional Contact Forms',
      'SEO Optimized Design',
    ],
  },
  {
    id: 3,
    title: 'TechStore - Computer Hardware Store',
    description:
      'A modern, responsive computer hardware store built with SvelteKit, TypeScript, and Tailwind CSS, deployed on Azure Static Web Apps. Features comprehensive product catalog with 8 categories (CPUs, GPUs, Storage, RAM, Motherboards, Cooling, PSUs, Cases), advanced shopping cart with quantity management, search & filter functionality, and fully responsive design optimized for desktop, tablet, and mobile.',
    technologies: ['SvelteKit 2.0', 'TypeScript', 'Tailwind CSS', 'Lucide Svelte', 'Azure Static Web Apps'],
    githubUrl: 'https://github.com/davidagustin/azure-static-practice',
    liveUrl: 'https://ashy-sky-078d0441e.2.azurestaticapps.net',
    icon: FaBolt,
    category: 'E-commerce',
    features: [
      '8 Product Categories',
      'Advanced Shopping Cart',
      'Search & Filter System',
      'Mobile-First Design',
    ],
  },
  {
    id: 4,
    title: '20 Newsgroups ML Analysis Dashboard',
    description:
      'A comprehensive machine learning analysis dashboard for the 20 Newsgroups dataset, featuring advanced hyperparameter tuning, model comparison, and interactive visualizations. Built with Next.js 15, Material-UI, and Python ML pipeline.',
    technologies: ['Next.js 15', 'React 18', 'TypeScript', 'Material-UI 5', 'Python', 'Scikit-learn', 'XGBoost', 'LightGBM', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/machine-learning-project',
    liveUrl: 'https://machine-learning-project-theta.vercel.app',
    icon: FaChartLine,
    category: 'AI/ML Dashboard',
    features: [
      '10+ ML Algorithms',
      'Interactive Visualizations',
      'Hyperparameter Tuning',
      'Real-time Model Comparison',
    ],
  },
  {
    id: 5,
    title: 'MLI Learning Quiz App',
    description:
      'A beautiful, interactive learning and mnemonic quiz application designed specifically for the MLI (Machine Learning Institute) precourse material. Features 5 quiz categories with smart mnemonics, progress analytics, and modern UI/UX.',
    technologies: ['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS 4', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/ai-quiz-questions',
    liveUrl: 'https://ai-quiz-questions.vercel.app',
    icon: FaGraduationCap,
    category: 'AI/ML Education',
    features: [
      '5 Quiz Categories',
      'Smart Mnemonics',
      'Progress Analytics',
      'Interactive Learning',
    ],
  },
  {
    id: 6,
    title: 'Hope Foundation',
    description:
      'A modern, responsive charity website built with Gatsby for Hope Foundation. Features donation systems, volunteer portals, event management, and comprehensive program showcases. Deployed on Digital Ocean with excellent performance and SEO optimization.',
    technologies: ['Gatsby', 'React', 'Digital Ocean', 'SEO Optimized', 'Responsive Design'],
    githubUrl: 'https://github.com/hope-foundation/charity-website',
    liveUrl: 'https://sample-gatsby-6fe3p.ondigitalocean.app/',
    icon: FaHeart,
    category: 'Charity/Non-Profit',
    features: [
      'Donation System',
      'Volunteer Portal',
      'Event Management',
      'Program Showcase',
    ],
  },
  {
    id: 7,
    title: 'Historigal',
    description:
      'A modern, responsive web application for searching through 37,860+ historical events from 300 B.C. to 2012 with a Google-like interface. Features advanced citation parsing, intelligent search with debouncing, URL routing, and mobile-first design.',
    technologies: ['Next.js 15', 'TypeScript 5', 'Tailwind CSS 3.3', 'React Hooks', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/historigal-vercel',
    liveUrl: 'https://historigal-vercel.vercel.app',
    icon: FaSearch,
    category: 'Data/Research',
    features: [
      '37,860+ historical events',
      'Advanced citation parsing',
      'Google-like autocomplete',
      'Mobile-first responsive',
    ],
  },
  {
    id: 8,
    title: 'AI Learning Hub',
    description:
      'A comprehensive Next.js application for learning AI and machine learning concepts through interactive mnemonics, character-based learning, and quizzes. Features 30+ learning sections with hundreds of quiz questions.',
    technologies: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'React Hooks', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/comprehensive-ai-learning-app',
    liveUrl: 'https://comprehensive-ai-learning-app.vercel.app',
    icon: FaBrain,
    category: 'Education/AI',
    features: [
      'Interactive Learning',
      'Hundreds of Quiz Questions',
      'Character-based Learning',
      '30+ AI/ML Topics',
    ],
  },
  {
    id: 9,
    title: 'A Very Nice Grocery List',
    description:
      'A modern, responsive grocery list application built with Next.js, React, and TypeScript. Features duplicate prevention, auto-scroll, and a beautiful dark theme with smooth animations.',
    technologies: ['Next.js 15', 'React 19', 'TypeScript', 'CSS3', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/a-very-nice-grocery-list-vercel',
    liveUrl: 'https://a-very-nice-grocery-list-vercel.vercel.app',
    icon: FaShoppingCart,
    category: 'Productivity',
    features: [
      'Add & Remove Items',
      'Duplicate Prevention',
      'Auto-scroll',
      'Dark Theme',
    ],
  },
  {
    id: 10,
    title: 'Luxury Realty',
    description:
      'A comprehensive, modern real estate website built with Angular and deployed on Surge.sh. Features luxury property listings with advanced search, filtering, interactive image galleries, and responsive design.',
    technologies: ['Angular 17', 'TypeScript', 'CSS3', 'Surge.sh', 'Google Fonts'],
    githubUrl: 'https://github.com/davidagustin/surge-practice',
    liveUrl: 'https://my-surge-practice-site.surge.sh',
    icon: FaHome,
    category: 'Real Estate',
    features: [
      'Property Listings & Search',
      'Advanced Filtering',
      'Interactive Galleries',
      'Responsive Design',
    ],
  },
  {
    id: 11,
    title: 'Elegant Furniture Store',
    description:
      'A modern, responsive furniture store built with Vue.js 3, Vite, and Tailwind CSS. Features a beautiful collection of premium furniture with shopping cart functionality, product catalog, and seamless user experience.',
    technologies: ['Vue.js 3', 'Vite 4', 'Tailwind CSS 3', 'Pinia 2', 'Vue Router 4', 'Render'],
    githubUrl: 'https://github.com/davidagustin/render-practice',
    liveUrl: 'https://render-practice-or72.onrender.com',
    icon: FaChair,
    category: 'E-commerce',
    features: [
      'Product Catalog & Search',
      'Shopping Cart System',
      'Responsive Design',
      'State Management',
    ],
  },
  {
    id: 12,
    title: 'Law & Associates',
    description:
      'A modern, professional law firm website built with Astro.js and Tailwind CSS. Features comprehensive legal services, attorney profiles, practice areas, and contact forms with a clean, professional design.',
    technologies: ['Astro.js', 'Tailwind CSS', 'TypeScript', 'Netlify'],
    githubUrl: 'https://github.com/davidagustin/netlify-practice',
    liveUrl: 'https://netlify-practice-one.netlify.app',
    icon: FaBalanceScale,
    category: 'Professional Services',
    features: [
      'Professional Design',
      'Practice Areas',
      'Team Profiles',
      'Contact Forms',
    ],
  },
  {
    id: 13,
    title: 'FoodRater - Restaurant Rating App',
    description:
      'A modern, responsive restaurant rating application built with Angular 17 and Firebase, inspired by Yelp. Features restaurant discovery, 5-star rating system, user authentication, real-time data, and beautiful UI with Material Design components.',
    technologies: ['Angular 17', 'Firebase', 'TypeScript', 'Tailwind CSS', 'Material Design', 'RxJS'],
    githubUrl: 'https://github.com/davidagustin/firebase-practice',
    liveUrl: 'https://firebase-practice--fir-practice-54eb3.us-central1.hosted.app/',
    icon: FaUtensils,
    category: 'Food & Rating',
    features: [
      'Restaurant Discovery',
      '5-Star Rating System',
      'User Authentication',
      'Real-time Data',
    ],
  },
  {
    id: 14,
    title: 'Sudoku Game',
    description:
      'A beautiful and interactive Sudoku game built with React and Express, deployed on Heroku. Features three difficulty levels (Easy, Medium, Hard), real-time validation, visual feedback with highlighted cells and error indicators, and modern UI with smooth animations.',
    technologies: ['React 18', 'Express.js', 'Node.js', 'Webpack 5', 'Heroku', 'CSS3'],
    githubUrl: 'https://github.com/davidagustin/heroku-practice',
    liveUrl: 'https://heroku-sudoku-49243446e4d3.herokuapp.com/',
    icon: FaPuzzlePiece,
    category: 'Gaming',
    features: [
      'Three Difficulty Levels',
      'Real-time Validation',
      'Interactive Gameplay',
      'Modern UI/UX',
    ],
  },
  {
    id: 15,
    title: 'Rules of Machine Learning - Memorization App',
    description:
      'A modern, interactive web application to help memorize Google\'s 43 Rules of Machine Learning Engineering. Features three study modes: Browse Mode with category filtering and search, Study Mode for sequential learning with progress tracking, and Flashcard Mode for randomized learning with navigation controls.',
    technologies: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/rules-of-machine-learning',
    liveUrl: 'https://rules-of-machine-learning.vercel.app/',
    icon: FaBook,
    category: 'AI/ML Education',
    features: [
      '43 ML Engineering Rules',
      'Three Study Modes',
      'Category Filtering',
      'Progress Tracking',
    ],
  },
  {
    id: 16,
    title: 'Sign Language Learning App',
    description:
      'Learn to spell your name in American Sign Language with real-time AI-powered hand tracking. Features MediaPipe hand recognition, personalized learning experience, visual guides, and comprehensive ASL alphabet reference with interactive feedback.',
    technologies: ['Next.js 15.4.5', 'React 19', 'TypeScript', 'Tailwind CSS', 'MediaPipe Hands', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/spell-your-name',
    liveUrl: 'https://spell-your-name.vercel.app/',
    icon: FaHandPaper,
    category: 'AI/ML Education',
    features: [
      'Real-time Hand Tracking',
      'AI-powered Gesture Recognition',
      'Personalized Learning',
      'ASL Alphabet Guide',
    ],
  },
  {
    id: 17,
    title: '🧠 System Design Learning Application',
    description:
      'A comprehensive, interactive learning platform designed to help developers master system design interviews through structured study materials, core concepts, interactive quizzes, and progress tracking. Features 50 study materials covering fundamentals to cutting-edge technologies, 40 core concepts with essential patterns and advanced principles, 60 quiz questions with progressive difficulty, and advanced progress tracking with dark mode support. Perfect for developers preparing for senior-level interviews at top tech companies.',
    technologies: ['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    githubUrl: 'https://github.com/davidagustin/system-design-practice',
    liveUrl: 'https://system-design-practice.vercel.app/',
    icon: FaLaptopCode,
    category: 'Education/System Design',
    features: [
      '50 Study Materials',
      '40 Core Concepts',
      '60 Quiz Questions',
      'Dark Mode Support',
    ],
  },
];
